### ISSUE TITLE
How to specify ffi functions

### ISSUE THREAD

**Issue by alegnani** [alegnani/pancake-verifier#19]

**Comment by JunmingZhao42** [comment]
Currently pancake FFI functions are all of the form `@func(x1, y1, x2, y2)` and they extend to C FFI functions as `void ffifunc(unsigned char *c, long clen, unsigned char *a, long alen)`. 
FFI functions can technically modify the heap under addresses `c` and `a`, but the current pancake driver code is only using it to interface with seL4 Microkit.
So probably for now it should be sufficient to have them as something like:
```
method ffi_func(x1: Int, y1: Int, x2: Int, y2: Int)
```
