### ISSUE TITLE
address assertions for memory ops

### ISSUE THREAD

**Issue by JunmingZhao42** [alegnani/pancake-verifier#48]
I noticed that there are assertions for addresses before memory operations, for example:
`!ld32 value, ptr;` would have assertion `assert ptr % 8 == 0`.
However in this case `ptr` is not necessarily word-size aligned, such as accessing 32-bit device registers.

I think perhaps for the shared memory ops, it'd make more sense if we just let users add assertions from the Pancake side?

**Comment by alegnani** [comment]
I agree that the check for the addresses being 8-byte aligned is definitely wrong.
 Aren't these register at least 4-byte aligned?

**Comment by JunmingZhao42** [comment]
Yes these registers are 4-byte aligned.
