### ISSUE TITLE
Resolve return type of functions

### ISSUE THREAD

**Issue by alegnani** [alegnani/pancake-verifier#5]

**Comment by JunmingZhao42** [comment]
For now it might make sense to just add annotations in the Pancake program for function return type (at the beginning of every pancake function), as something like:
```
// option 1:
/*@ return (retval: IArray) @*/
// option 2:
/*@ return (retval: Int) @*/
```
(when I change `Int` to `IArray` it seems sufficient for Pancake functions returning various shapes (in the Pancake driver).)
